assetic:
    bundles: [ AnimeDbShikimoriSimilarItemsWidgetBundle ]
    assets:
        stylesheets:
            inputs:
                - @AnimeDbShikimoriSimilarItemsWidgetBundle/Resources/public/css/*.css